export const FETCH_PIPELINE_REQUEST = "FETCH_PIPELINE_REQUEST";
export const FETCH_PIPELINE_SUCCESS = "FETCH_PIPELINE_SUCCESS";
export const FETCH_PIPELINE_FAILURE = "FETCH_PIPELINE_FAILURE";
export const FETCH_ALLPROJECTS_REQUEST = " FETCH_ALLPROJECTS_REQUEST";
export const FETCH_ALLPROJECTS_SUCCESS = "FETCH_ALLPROJECTS_SUCCESS";
export const FETCH_ALLPROJECTS_FAILURE = "FETCH_ALLPROJECTS_FAILURE";