export const FETCH_PIPELINE_REQUEST = "FETCH_PIPELINE_REQUEST";
export const FETCH_PIPELINE_SUCCESS = "FETCH_PIPELINE_SUCCESS";
export const FETCH_PIPELINE_FAILURE = "FETCH_PIPELINE_FAILURE";
export const FETCH_ALLPROJECTS_REQUEST = " FETCH_ALLPROJECTS_REQUEST";
export const FETCH_ALLPROJECTS_SUCCESS = "FETCH_ALLPROJECTS_SUCCESS";
export const FETCH_ALLPROJECTS_FAILURE = "FETCH_ALLPROJECTS_FAILURE";
export const FETCH_RECORDS = "FETCH_RECORDS ";
export const FETCH_RECORDS_SUCCESS = "FETCH_RECORDS_SUCCESS "
export const FETCH_RECORDS_FAILURE = "FETCH_RECORDS_FAILURE ";


export const FETCH_ALLGROUP_DATA_REQUEST = "FETCH_ALLGROUP_DATA_REQUEST";
export const FETCH_ALLGROUP_DATA_SUCCESS = "FETCH_ALLGROUP_DATA_SUCCESS";
export const FETCH_ALLGROUP_DATA_FAILURE = "FETCH_ALLGROUP_DATA_FAILURE";

export const FETCH_PROJECT_BYID_REQUEST = " FETCH_PROJECT_BYID_REQUEST";
export const FETCH_PROJECT_BYID_SUCCESS = "FETCH_PROJECT_BYID_SUCCESS";
export const FETCH_PROJECT_BYID_FAILURE = "FETCH_PROJECT_BYID_FAILURE";


export const DB_CONNECTION_REQUEST = 'DB_CONNECTION_REQUEST';
export const DB_CONNECTION_SUCCESS = 'DB_CONNECTION_SUCCESS';
export const DB_CONNECTION_FAILURE = 'DB_CONNECTION_FAILURE';
