export const FETCH_COMPOSE_PIPELINE = "FETCH_COMPOSE_PIPELINE";
export const FETCH_COMPOSE_PIPELINE_SUCCESS = "FETCH_COMPOSE_PIPELINE_SUCCESS";
export const FETCH_COMPOSE_PIPELINE_FAILURE = "FETCH_COMPOSE_PIPELINE_FAILURE";

export const FETCH_REPORTS_PIPELINE="FETCH_REPORTS_PIPELINE";
export const FETCH_REPORTS_PIPELINE_SUCCESS="FETCH_REPORTS_PIPELINE_SUCCESS";
export const FETCH_REPORTS_PIPELINE_FAILURE="FETCH_REPORTS_PIPELINE_FAILURE";

export const FETCH_SCHEMA_COMPOSE = 'FETCH_SCHEMA_COMPOSE';
export const FETCH_SCHEMA_COMPOSE_SUCCESS = 'FETCH_SCHEMA_COMPOSE_SUCCESS ';
export const FETCH_SCHEMA_COMPOSE_FAILURE = 'FETCH_SCHEMA_COMPOSE_FAILURE';


