export const FETCH_COMPOSE_PIPELINE = "FETCH_COMPOSE_PIPELINE";
export const FETCH_COMPOSE_PIPELINE_SUCCESS = "FETCH_COMPOSE_PIPELINE_SUCCESS";
export const FETCH_COMPOSE_PIPELINE_FAILURE = "FETCH_COMPOSE_PIPELINE_FAILURE";

export const FETCH_REPORTS_PIPELINE="FETCH_REPORTS_PIPELINE";
export const FETCH_REPORTS_PIPELINE_SUCCESS="FETCH_REPORTS_PIPELINE_SUCCESS";
export const FETCH_REPORTS_PIPELINE_FAILURE="FETCH_REPORTS_PIPELINE_FAILURE";

export const FETCH_PROJECT_SCHEMA_INFO_ACTION = 'FETCH_PROJECT_SCHEMA_INFO_ACTION';
export const FETCH_PROJECT_SCHEMA_INFO_ACTION_SUCCESS = 'FETCH_PROJECT_SCHEMA_INFO_ACTION_SUCCESS ';
export const FETCH_PROJECT_SCHEMA_INFO_ACTION_FAILURE = 'FETCH_PROJECT_SCHEMA_INFO_ACTION_FAILURE';

export const POST_PROJECT_SCHEMA_INFO_ACTION = 'POST_PROJECT_SCHEMA_INFO_ACTION';
export const POST_PROJECT_SCHEMA_INFO_ACTION_SUCCESS = 'POST_PROJECT_SCHEMA_INFO_ACTION_SUCCESS ';
export const POST_PROJECT_SCHEMA_INFO_ACTION_FAILURE = 'POST_PROJECT_SCHEMA_INFO_ACTION_FAILURE';


export const DELETE_PROJECT_SCHEMA_INFO_ACTION = 'DELETE_PROJECT_SCHEMA_INFO_ACTION';
export const DELETE_PROJECT_SCHEMA_INFO_ACTION_SUCCESS = 'DELETE_PROJECT_SCHEMA_INFO_ACTION_SUCCESS ';
export const DELETE_PROJECT_SCHEMA_INFO_ACTION_FAILURE = 'DELETE_PROJECT_SCHEMA_INFO_ACTION_FAILURE';


export const SEARCH_SCHEMA_BY_TAG_INFO_ACTION='SEARCH_SCHEMA_BY_TAG_INFO_ACTION';
export const SEARCH_SCHEMA_BY_TAG_INFO_ACTION_SUCCESS='SEARCH_SCHEMA_BY_TAG_INFO_ACTION_SUCCESS';
export const SEARCH_SCHEMA_BY_TAG_INFO_ACTION_FAILURE='SEARCH_SCHEMA_BY_TAG_INFO_ACTION_FAILURE';

//to save name & desc of project in db
export const POST_COMPOSE_NAME_DESC="POST_COMPOSE_NAME_DESC";
export const POST_COMPOSE_NAME_DESC_SUCCESS="POST_COMPOSE_NAME_DESC_SUCCESS";
export const POST_COMPOSE_NAME_DESC_FAILURE="POST_COMPOSE_NAME_DESC_FAILURE";

//to get id,name,desc of project in redux object 
export const GET_COMPOSE_NAME_DESC="GET_COMPOSE_NAME_DESC";
export const GET_COMPOSE_NAME_DESC_SUCCESS="GET_COMPOSE_NAME_DESC_SUCCESS";
export const GET_COMPOSE_NAME_DESC_FAILURE="GET_COMPOSE_NAME_DESC_FAILURE";
//to add uid,name,desc to a array
export const ADD_NAME_DESC_ARRAY = 'ADD_NAME_DESC_ARRAY';
