export const FETCH_COMPOSE_PIPELINE = "FETCH_COMPOSE_PIPELINE";
export const FETCH_COMPOSE_PIPELINE_SUCCESS = "FETCH_COMPOSE_PIPELINE_SUCCESS";
export const FETCH_COMPOSE_PIPELINE_FAILURE = "FETCH_COMPOSE_PIPELINE_FAILURE";

export const FETCH_REPORTS_PIPELINE="FETCH_REPORTS_PIPELINE";
export const FETCH_REPORTS_PIPELINE_SUCCESS="FETCH_REPORTS_PIPELINE_SUCCESS";
export const FETCH_REPORTS_PIPELINE_FAILURE="FETCH_REPORTS_PIPELINE_FAILURE";

export const FETCH_PROJECT_SCHEMA_INFO_ACTION = 'FETCH_PROJECT_SCHEMA_INFO_ACTION';
export const FETCH_PROJECT_SCHEMA_INFO_ACTION_SUCCESS = 'FETCH_PROJECT_SCHEMA_INFO_ACTION_SUCCESS ';
export const FETCH_PROJECT_SCHEMA_INFO_ACTION_FAILURE = 'FETCH_PROJECT_SCHEMA_INFO_ACTION_FAILURE';

export const POST_PROJECT_SCHEMA_INFO_ACTION = 'POST_PROJECT_SCHEMA_INFO_ACTION';
export const POST_PROJECT_SCHEMA_INFO_ACTION_SUCCESS = 'POST_PROJECT_SCHEMA_INFO_ACTION_SUCCESS ';
export const POST_PROJECT_SCHEMA_INFO_ACTION_FAILURE = 'POST_PROJECT_SCHEMA_INFO_ACTION_FAILURE';


export const DELETE_PROJECT_SCHEMA_INFO_ACTION = 'DELETE_PROJECT_SCHEMA_INFO_ACTION';
export const DELETE_PROJECT_SCHEMA_INFO_ACTION_SUCCESS = 'DELETE_PROJECT_SCHEMA_INFO_ACTION_SUCCESS ';
export const DELETE_PROJECT_SCHEMA_INFO_ACTION_FAILURE = 'DELETE_PROJECT_SCHEMA_INFO_ACTION_FAILURE';


