export const POST_GROUP_PIPELINE_ACTION = 'POST_GROUP_PIPELINE_ACTION';
export const POST_GROUP_PIPELINE_ACTION_SUCCESS = 'POST_GROUP_PIPELINE_ACTION_SUCCESS';
export const POST_GROUP_PIPELINE_ACTION_FAILURE = 'POST_GROUP_PIPELINE_ACTION_FAILURE';