export const FETCH_ALLPROJECTS_REQUEST = " FETCH_ALLPROJECTS_REQUEST";
export const FETCH_ALLPROJECTS_SUCCESS = "FETCH_ALLPROJECTS_SUCCESS";
export const FETCH_ALLPROJECTS_FAILURE = "FETCH_ALLPROJECTS_FAILURE";