export const FETCH_ALLPROJECTS_REQUEST = " FETCH_ALLPROJECTS_REQUEST";
export const FETCH_ALLPROJECTS_SUCCESS = "FETCH_ALLPROJECTS_SUCCESS";
export const FETCH_ALLPROJECTS_FAILURE = "FETCH_ALLPROJECTS_FAILURE";

export const DELETE_PROJECTS_INFO_ACTION = " DELETE_PROJECTS_INFO_ACTION";
export const DELETE_PROJECTS_INFO_ACTION_SUCCESS = "DELETE_PROJECTS_INFO_ACTION_SUCCESS";
export const DELETE_PROJECTS_INFO_ACTION_FAILURE = "DELETE_PROJECTS_INFO_ACTION_FAILURE";

export const DELETE_PROJECTGROUPS_INFO_ACTION = " DELETE_PROJECTGROUPS_INFO_ACTION";
export const DELETE_PROJECTGROUPS_ACTION_SUCCESS = "DELETE_PROJECTGROUPS_INFO_ACTION_SUCCESS";
export const DELETE_PROJECTGROUPS_INFO_ACTION_FAILURE = "DELETE_PROJECTGROUPS_INFO_ACTION_FAILURE";