export const FETCH_SCHEMA_SCHEMADATA = "FETCH_SCHEMA_SCHEMADATA";
export const FETCH_SCHEMA_SCHEMADATA_SUCCESS = "FETCH_SCHEMA_SCHEMADATA_SUCCESS";
export const FETCH_SCHEMA_SCHEMADATA_FAILURE = "FETCH_SCHEMA_SCHEMADATA_FAILURE";

export const FETCH_SCHEMA_DATABASE = "FETCH_SCHEMA_DATABASE";
export const FETCH_SCHEMA_DATABASE_SUCCESS = "FETCH_SCHEMA_DATABASE_SUCCESS";
export const FETCH_SCHEMA_DATABASE_FAILURE = "FETCH_SCHEMA_DATABASE_FAILURE";

export const FETCH_GROUPDATA_DATABASE = "FETCH_GROUPDATA_DATABASE";
export const FETCH_GROUPDATA_DATABASE_SUCCESS = "FETCH_GROUPDATA_DATABASE_SUCCESS";
export const FETCH_GROUPDATA_DATABASE_FAILURE = "FETCH_GROUPDATA_DATABASE_FAILURE";
export const ADD_GROUPDATA_ARRAY = 'ADD_GROUPDATA_ARRAY';

export const REMOVE_NODE = 'REMOVE_NODE';
export const ADD_ARRAY = 'ADD_ARRAY';

export const POST_GROUPDATA_DATABASE = "POST_GROUPDATA_DATABASE";
export const POST_GROUPDATA_DATABASE_SUCCESS = "POST_GROUPDATA_DATABASE_SUCCESS";
export const POST_GROUPDATA_DATABASE_FAILURE = "POST_GROUPDATA_DATABASE_FAILURE";

export const ADD_LAST_INDEX = "ADD_LAST_INDEX";
export const REMOVE_LAST_INDEX = "REMOVE_LAST_INDEX";
export const CLEAR_LAST_INDEXES = "CLEAR_LAST_INDEXES";

export const POST_GROUPDATA = "POST_GROUPDATA";
export const POST_GROUPDATA_SUCCESS = "POST_GROUPDATA_SUCCESS";
export const POST_GROUPDATA_FAILURE = "POST_GROUPDATA_FAILURE";

export const FETCH_SCHEMA_DATA="FETCH_SCHEMA_DATA";
export const FETCH_SCHEMA_DATA_SUCCESS="FETCH_SCHEMA_DATA_SUCCESS";
export const FETCH_SCHEMA_DATA_FAILURE="FETCH_SCHEMA_DATA_FAILURE";
export const FETCH_ALLGROUP_DATA="FETCH_ALLGROUP_DATA";
