export const FETCH_SCHEMA_SCHEMADATA_INFO_ACTION = "FETCH_SCHEMA_SCHEMADATA_INFO_ACTION";
export const FETCH_SCHEMA_SCHEMADATA_INFO_ACTION_SUCCESS = "FETCH_SCHEMA_SCHEMADATA_INFO_ACTION_SUCCESS";
export const FETCH_SCHEMA_SCHEMADATA_INFO_ACTION_FAILURE = "FETCH_SCHEMA_SCHEMADATA_INFO_ACTION_FAILURE";

export const FETCH_SCHEMA_DATABASE_INFO_ACTION = "FETCH_SCHEMA_DATABASE_INFO_ACTION";
export const FETCH_SCHEMA_DATABASE_INFO_ACTION_SUCCESS = "FETCH_SCHEMA_DATABASE_INFO_ACTION_SUCCESS";
export const FETCH_SCHEMA_DATABASE_INFO_ACTION_FAILURE = "FETCH_SCHEMA_DATABASE_INFO_ACTION_FAILURE";

export const FETCH_GROUPDATA_DATABASE = "FETCH_GROUPDATA_DATABASE";
export const FETCH_GROUPDATA_DATABASE_SUCCESS = "FETCH_GROUPDATA_DATABASE_SUCCESS";
export const FETCH_GROUPDATA_DATABASE_FAILURE = "FETCH_GROUPDATA_DATABASE_FAILURE";
export const ADD_GROUPDATA_ARRAY = 'ADD_GROUPDATA_ARRAY';

export const REMOVE_NODE = 'REMOVE_NODE';
export const ADD_ARRAY = 'ADD_ARRAY';

export const POST_GROUPDATA_DATABASE = "POST_GROUPDATA_DATABASE";
export const POST_GROUPDATA_DATABASE_SUCCESS = "POST_GROUPDATA_DATABASE_SUCCESS";
export const POST_GROUPDATA_DATABASE_FAILURE = "POST_GROUPDATA_DATABASE_FAILURE";

export const ADD_LAST_INDEX = "ADD_LAST_INDEX";
export const REMOVE_LAST_INDEX = "REMOVE_LAST_INDEX";
export const CLEAR_LAST_INDEXES = "CLEAR_LAST_INDEXES";
export const DELETE_GROUP_MODAL_BOX = "DELETE_GROUP_MODAL_BOX";



export const ADD_ATTRIBUTE_DETAILS = "ADD_ATTRIBUTE_DETAILS";
export const POST_GROUPDATA = "POST_GROUPDATA";
export const POST_GROUPDATA_SUCCESS = "POST_GROUPDATA_SUCCESS";
export const POST_GROUPDATA_FAILURE = "POST_GROUPDATA_FAILURE";

export const FETCH_SCHEMA_DATA = "FETCH_SCHEMA_DATA";
export const FETCH_SCHEMA_DATA_SUCCESS = "FETCH_SCHEMA_DATA_SUCCESS";
export const FETCH_SCHEMA_DATA_FAILURE = "FETCH_SCHEMA_DATA_FAILURE";
export const FETCH_ALLGROUP_DATA = "FETCH_ALLGROUP_DATA";

export const POST_TAGS_DESCRIPTION_INFO_ACTION = 'POST_TAGS_DESCRIPTION_REQUEST_INFO_ACTION';
export const POST_TAGS_DESCRIPTION_INFO_ACTION_SUCCESS = 'POST_TAGS_DESCRIPTION_INFO_ACTION_SUCCESS';
export const POST_TAGS_DESCRIPTION_INFO_ACTION_FAILURE = 'POST_TAGS_DESCRIPTION_INFO_ACTION_FAILURE';

export const POST_COLUMN_TAGS_DESCRIPTION_INFO_ACTION = 'POST_COLUMN_TAGS_DESCRIPTION_INFO_ACTION';
export const POST_COLUMN_TAGS_DESCRIPTION_INFO_ACTION_SUCCESS = 'POST_COLUMN_TAGS_DESCRIPTION_INFO_ACTION_SUCCESS';
export const POST_COLUMN_TAGS_DESCRIPTION_INFO_ACTION_FAILURE = 'POST_COLUMN_TAGS_DESCRIPTION__INFO_ACTION_FAILURE';
