export const FETCH_SCHEMA_SCHEMADATA = "FETCH_SCHEMA_SCHEMADATA";
export const FETCH_SCHEMA_SCHEMADATA_SUCCESS = "FETCH_SCHEMA_SCHEMADATA_SUCCESS";
export const FETCH_SCHEMA_SCHEMADATA_FAILURE = "FETCH_SCHEMA_SCHEMADATA_FAILURE";

export const FETCH_SCHEMA_DATABASE = "FETCH_SCHEMA_DATABASE";
export const FETCH_SCHEMA_DATABASE_SUCCESS = "FETCH_SCHEMA_DATABASE_SUCCESS";
export const FETCH_SCHEMA_DATABASE_FAILURE = "FETCH_SCHEMA_DATABASE_FAILURE";

export const FETCH_GROUPDATA_DATABASE = "FETCH_GROUPDATA_DATABASE";
export const FETCH_GROUPDATA_DATABASE_SUCCESS = "FETCH_GROUPDATA_DATABASE_SUCCESS";
export const FETCH_GROUPDATA_DATABASE_FAILURE = "FETCH_GROUPDATA_DATABASE_FAILURE";
export const REMOVE_NODE = 'REMOVE_NODE';
export const ADD_ARRAY = 'ADD_ARRAY';

export const POST_GROUPDATA_DATABASE = "POST_GROUPDATA_DATABASE";
export const POST_GROUPDATA_DATABASE_SUCCESS = "POST_GROUPDATA_DATABASE_SUCCESS";
export const POST_GROUPDATA_DATABASE_FAILURE = "POST_GROUPDATA_DATABASE_FAILURE";
