export const NAME_ERROR = "name can not be empty"
export const DESCRIPTION_ERROR = 'description can not be empty'
export const NAME_DESCRIPTION_ERROR = "name and description can not be empty"
export const TEXTAREA_ERROR = "textAreaError"
export const DELETE_TOAST = "Deleted Successfully"
export const SUCCESSTOAST = "Saved Successfully"
export const ERRORTOAST = "Failed to Save"
export const SAVE_CONFIRMATION = "Save Confirmation"
export const SAVE_CONFIRMATION_MESSAGE = "Are you sure you want to save?"
export const CANCEL_CONFIRMATION = "Cancel Confirmation"
export const CANCEL_CONFIRMATION_MESSAGE = "Are you sure you want to cancel?"
export const INITIAL = "initial"
export const SYNC = "sync"
export const NOW = "Now"
export const TODAY = "Today"
export const DAILY = "Daily"
export const WEEKLY = "Weekly"
export const MONTHLY = "Monthly"
export const MONDAY = "Monday"
export const TUESDAY = "Tuesday";
export const WEDNESDAY = "Wednesday";
export const THURSDAY = "Thursday";
export const FRIDAY = "Friday";
export const SATURDAY = "Saturday";
export const SUNDAY = "Sunday";
export const IMPORTSUCCESS="Imported Successfully";
export const IMPORTERROR="Importing Failed";
export const IMPORT="Import";
export const NO_DATA="No Data";
export const REMOVE="REMOVE";
export const DELETESUCCESS="Deleted Successfully";
export const DELETEERROR="Deleting Failed";
export const SCHEMA="Schema";

